In [1]:
import numpy as np
import pandas as pd

In [2]:
happy_df=pd.read_csv("ACME-HappinessSurvey2020.csv")

In [3]:
happy_df

Y  X1  X2  X3  X4  X5  X6
0    0   3   3   3   4   2   4
1    0   3   2   3   5   4   3
2    1   5   3   3   3   3   5
3    0   5   4   3   3   3   5
4    0   5   4   3   3   3   5
..  ..  ..  ..  ..  ..  ..  ..
121  1   5   2   3   4   4   3
122  1   5   2   3   4   2   5
123  1   5   3   3   4   4   5
124  0   4   3   3   4   4   5
125  0   5   3   2   5   5   5

[126 rows x 7 columns]

Data Description:

Y = target attribute (Y) with values indicating 0 (unhappy) and 1 (happy) customers

X1 = my order was delivered on time

X2 = contents of my order was as I expected

X3 = I ordered everything I wanted to order

X4 = I paid a good price for my order

X5 = I am satisfied with my courier

X6 = the app makes ordering easy for me


In [4]:
happy_df.shape

(126, 7)

In [5]:
happy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126 entries, 0 to 125
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Y       126 non-null    int64
 1   X1      126 non-null    int64
 2   X2      126 non-null    int64
 3   X3      126 non-null    int64
 4   X4      126 non-null    int64
 5   X5      126 non-null    int64
 6   X6      126 non-null    int64
dtypes: int64(7)
memory usage: 7.0 KB


In [6]:
happy_df.describe(include = "all")

Y          X1          X2          X3          X4          X5  \
count  126.000000  126.000000  126.000000  126.000000  126.000000  126.000000   
mean     0.547619    4.333333    2.531746    3.309524    3.746032    3.650794   
std      0.499714    0.800000    1.114892    1.023440    0.875776    1.147641   
min      0.000000    1.000000    1.000000    1.000000    1.000000    1.000000   
25%      0.000000    4.000000    2.000000    3.000000    3.000000    3.000000   
50%      1.000000    5.000000    3.000000    3.000000    4.000000    4.000000   
75%      1.000000    5.000000    3.000000    4.000000    4.000000    4.000000   
max      1.000000    5.000000    5.000000    5.000000    5.000000    5.000000   

               X6  
count  126.000000  
mean     4.253968  
std      0.809311  
min      1.000000  
25%      4.000000  
50%      4.000000  
75%      5.000000  
max      5.000000

In [7]:
## skewness and kurtosis

print("Skewness: ", "\n", happy_df.skew())
print(" ")
print("Kurtosis: ", "\n", happy_df.kurtosis())

Skewness:  
 Y    -0.193659
X1   -1.058468
X2    0.271000
X3   -0.199536
X4   -0.422240
X5   -0.699999
X6   -0.957590
dtype: float64
 
Kurtosis:  
 Y    -1.994412
X1    1.024968
X2   -0.601168
X3   -0.111410
X4    0.278617
X5   -0.306418
X6    0.941835
dtype: float64


In [8]:
## Check Multicollinearity

happy_df.corr(method = "pearson")

Y        X1        X2        X3        X4        X5        X6
Y   1.000000  0.280160 -0.024274  0.150838  0.064415  0.224522  0.167669
X1  0.280160  1.000000  0.059797  0.283358  0.087541  0.432772  0.411873
X2 -0.024274  0.059797  1.000000  0.184129  0.114838  0.039996 -0.062205
X3  0.150838  0.283358  0.184129  1.000000  0.302618  0.358397  0.203750
X4  0.064415  0.087541  0.114838  0.302618  1.000000  0.293115  0.215888
X5  0.224522  0.432772  0.039996  0.358397  0.293115  1.000000  0.320195
X6  0.167669  0.411873 -0.062205  0.203750  0.215888  0.320195  1.000000

In [9]:
## Check Multicollinearity

happy_df.corr(method = "pearson") > 0.85

Y     X1     X2     X3     X4     X5     X6
Y    True  False  False  False  False  False  False
X1  False   True  False  False  False  False  False
X2  False  False   True  False  False  False  False
X3  False  False  False   True  False  False  False
X4  False  False  False  False   True  False  False
X5  False  False  False  False  False   True  False
X6  False  False  False  False  False  False   True

# split data into training and testing

In [10]:
# Create our features
y = happy_df["Y"]
X = happy_df.drop("Y", axis=1)
X

X1  X2  X3  X4  X5  X6
0     3   3   3   4   2   4
1     3   2   3   5   4   3
2     5   3   3   3   3   5
3     5   4   3   3   3   5
4     5   4   3   3   3   5
..   ..  ..  ..  ..  ..  ..
121   5   2   3   4   4   3
122   5   2   3   4   2   5
123   5   3   3   4   4   5
124   4   3   3   4   4   5
125   5   3   2   5   5   5

[126 rows x 6 columns]

In [11]:
# Check the balance of our target values
y.value_counts()

1    69
0    57
Name: Y, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

# Logistic Regression

In [13]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs', random_state=1)
classifier

LogisticRegression(random_state=1)

In [14]:
classifier.fit(X_train, y_train)
prediction = classifier.predict(X_test)
pd.DataFrame({"Prediction": prediction, "Actual": y_test})

Prediction  Actual
120           0       0
46            1       1
73            1       0
90            0       0
102           1       0
53            1       1
119           0       1
124           1       0
116           0       1
42            1       0
91            1       1
51            1       1
106           1       1
35            1       0
44            0       1
118           0       1
74            1       1
104           1       0
123           1       1
2             1       1
54            0       1
108           1       0
111           1       0
48            1       1
33            0       1
95            1       1
67            1       0
82            1       1
17            1       1
97            1       1
31            1       0
45            1       1

In [15]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, prediction)

0.5

In [16]:
from sklearn.metrics import confusion_matrix
# Calculating the confusion matrix.

confusion_matrix(y_test, prediction)

array([[ 2, 10],
       [ 6, 14]], dtype=int64)

In [17]:
from sklearn.metrics import classification_report
# Print the imbalanced classification report
report1 = classification_report(y_test, prediction)
print(report1)

              precision    recall  f1-score   support

           0       0.25      0.17      0.20        12
           1       0.58      0.70      0.64        20

    accuracy                           0.50        32
   macro avg       0.42      0.43      0.42        32
weighted avg       0.46      0.50      0.47        32



# Support vector machine

In [18]:
from sklearn.svm import SVC
model = SVC(kernel='linear')

In [19]:
model.fit(X_train, y_train)

SVC(kernel='linear')

In [20]:
y_pred = model.predict(X_test)
results = pd.DataFrame({
   "Prediction": y_pred,
   "Actual": y_test
}).reset_index(drop=True)
results.head()

Prediction  Actual
0           0       0
1           1       1
2           1       0
3           0       0
4           1       0

In [21]:

accuracy_score(y_test, y_pred)

0.5

In [22]:
confusion_matrix(y_test, y_pred)

array([[ 2, 10],
       [ 6, 14]], dtype=int64)

In [23]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.25      0.17      0.20        12
           1       0.58      0.70      0.64        20

    accuracy                           0.50        32
   macro avg       0.42      0.43      0.42        32
weighted avg       0.46      0.50      0.47        32



# Decision Tree

In [24]:
from sklearn import tree
# Creating the decision tree classifier instance.
model = tree.DecisionTreeClassifier()
# Fitting the model.
model = model.fit(X_train, y_train)

In [25]:
# Making predictions using the testing data.
pred = model.predict(X_test)

In [26]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, pred)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df


Predicted 0  Predicted 1
Actual 0            3            9
Actual 1            7           13

In [27]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, pred)
acc_score

0.5

In [28]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, pred))

Confusion Matrix


Predicted 0  Predicted 1
Actual 0            3            9
Actual 1            7           13

Accuracy Score : 0.5
Classification Report
              precision    recall  f1-score   support

           0       0.30      0.25      0.27        12
           1       0.59      0.65      0.62        20

    accuracy                           0.50        32
   macro avg       0.45      0.45      0.45        32
weighted avg       0.48      0.50      0.49        32



# Random Forest

In [29]:
# Resample the training data with the BalancedRandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier
rf_model = BalancedRandomForestClassifier(n_estimators=100,random_state=1) 
rf_model

BalancedRandomForestClassifier(random_state=1)

In [30]:

# Calculated the balanced accuracy score
# Fitting the model
rf_model = rf_model.fit(X_train, y_train)
# Making predictions using the testing data.
predictions = rf_model.predict(X_test)

acc_score = accuracy_score(y_test, predictions)
acc_score

0.5

In [31]:

# Calculating the confusion matrix.

confusion_matrix(y_test, predictions)


array([[ 3,  9],
       [ 7, 13]], dtype=int64)

In [32]:

# Print the imbalanced classification report
report = classification_report(y_test, predictions)
print(report)

              precision    recall  f1-score   support

           0       0.30      0.25      0.27        12
           1       0.59      0.65      0.62        20

    accuracy                           0.50        32
   macro avg       0.45      0.45      0.45        32
weighted avg       0.48      0.50      0.49        32



In [33]:
# List the features sorted in descending order by feature importance
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.19514199223347004, 'X3'),
 (0.18031493484498767, 'X2'),
 (0.17717697292172896, 'X5'),
 (0.16119979851553576, 'X1'),
 (0.1454983887284093, 'X6'),
 (0.1406679127558683, 'X4')]

# Easy Ensemble AdaBoost Classifier

In [34]:
# Train the EasyEnsembleClassifier
from imblearn.ensemble import EasyEnsembleClassifier

eec = EasyEnsembleClassifier(n_estimators=100, random_state=1)
eec.fit(X_train, y_train)

predictions = eec.predict(X_test)

In [35]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score

balanced_accuracy_score(y_test, predictions)

0.65

In [36]:
# Display the confusion matrix
y_pred = eec.predict(X_test)
confusion_matrix(y_test, predictions)

array([[ 6,  6],
       [ 4, 16]], dtype=int64)

In [37]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.60      0.50      0.80      0.55      0.63      0.39        12
          1       0.73      0.80      0.50      0.76      0.63      0.41        20

avg / total       0.68      0.69      0.61      0.68      0.63      0.40        32

